import os
import shutil
from pathlib import Path
from typing import List

from tests.utils import assert_file_exists, setup_output_file
from workflows.context import WorkflowContext
from workflows.schemas import WorkflowOutput


def save_and_assert_workflow_outputs(context: WorkflowContext, result: List[WorkflowOutput], workflow_name: str):
    assert len(result) > 0, "No outputs were generated by the workflow."

    for i, output in enumerate(result):
        path = context.validate_and_save_output(output)
        extension = Path(path).suffix.lstrip(".")
        output_name = setup_output_file("workflows", workflow_name, suffix=f"{i}", extension=extension)

        if os.path.exists(path):
            shutil.copy(path, output_name)

        assert_file_exists(output_name)
